---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phe-app
  namespace: dev-phe-app
  labels:
    app: phe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phe-app
  template:
    metadata:
      labels:
        app: phe-app
    spec:
      containers:
        - name: phe-app
          image: philippehenin/phe-app:v0.1.1
          ports:
            - containerPort: 80
